const CartActionTypes = {
    ADD_PRODUCT: 'ADD_PRODUCT',
    QUANTITY_CHANGED: 'QUANTITY_CHANGED',
    CLEAR_PRODUCT_FROM_SUMM: 'CLEAR_PRODUCT_FROM_SUMM',
    REMOVE_PRODUCT: 'REMOVE_PRODUCT'
};

export default CartActionTypes;